CREATE TABLE `players` (
  `PLAYER_NAME` text DEFAULT NULL,
  `TEAM_ID` int(11) DEFAULT NULL,
  `PLAYER_ID` int(11) DEFAULT NULL,
  `SEASON` int(11) DEFAULT NULL
) ;

CREATE TABLE `ranking` (
  `TEAM_ID` int(11) DEFAULT NULL,
  `LEAGUE_ID` text DEFAULT NULL,
  `SEASON_ID` int(11) DEFAULT NULL,
  `STANDINGSDATE` text DEFAULT NULL,
  `CONFERENCE` text DEFAULT NULL,
  `TEAM` text DEFAULT NULL,
  `G` int(11) DEFAULT NULL,
  `W` int(11) DEFAULT NULL,
  `L` int(11) DEFAULT NULL,
  `W_PCT` text DEFAULT NULL,
  `HOME_RECORD` text DEFAULT NULL,
  `ROAD_RECORD` text DEFAULT NULL
) ;

CREATE TABLE `teams` (
  `LEAGUE_ID` text DEFAULT NULL,
  `TEAM_ID` int(11) DEFAULT NULL,
  `MIN_YEAR` int(11) DEFAULT NULL,
  `MAX_YEAR` int(11) DEFAULT NULL,
  `ABBREVIATION` text DEFAULT NULL,
  `NICKNAME` text DEFAULT NULL,
  `YEARFOUNDED` int(11) DEFAULT NULL,
  `CITY` text DEFAULT NULL,
  `ARENA` text DEFAULT NULL,
  `ARENACAPACITY` text DEFAULT NULL,
  `OWNER` text DEFAULT NULL,
  `GENERALMANAGER` text DEFAULT NULL,
  `HEADCOACH` text DEFAULT NULL,
  `DLEAGUEAFFILIATION` text DEFAULT NULL
) ;
